import { GoogleGenerativeAI } from '@google/generative-ai';

// ============================================================
// SMART AI AGENT — Every answer is generated live by Gemini.
// No hardcoded knowledge base, no canned greetings, no
// Wikipedia fallback. The only "fixed" text left is the
// handful of error messages shown when Gemini truly cannot
// be reached (no key / no internet / quota) — those can't be
// generated by the AI because the AI is exactly what's down.
// ============================================================

const LANGUAGE_NAMES = {
  en: 'English',
  hi: 'Hindi (हिन्दी)',
  as: 'Assamese (অসমীয়া)',
  bn: 'Bengali (বাংলা)',
  mr: 'Marathi (मराठी)',
  gu: 'Gujarati (ગુજરાતી)',
  pa: 'Punjabi (ਪੰਜਾਬੀ)',
  or: 'Odia (ଓଡ଼ିଆ)',
  te: 'Telugu (తెలుగు)',
  ta: 'Tamil (தமிழ்)',
  kn: 'Kannada (ಕನ್ನಡ)',
};

// Unicode script ranges used to guess the language straight from what the
// user typed, so the reply matches even if the UI's language selector is
// wrong, missing, or the user just switches languages mid-conversation.
// Devanagari (hi/mr) and Bengali (bn/as) scripts are shared by two
// languages each — we default to the more common one (hi, bn) unless the
// caller tells us otherwise via `preferredLang`.
const SCRIPT_RANGES = [
  { lang: 'pa', regex: /[\u0A00-\u0A7F]/ }, // Gurmukhi
  { lang: 'gu', regex: /[\u0A80-\u0AFF]/ }, // Gujarati
  { lang: 'or', regex: /[\u0B00-\u0B7F]/ }, // Odia
  { lang: 'ta', regex: /[\u0B80-\u0BFF]/ }, // Tamil
  { lang: 'te', regex: /[\u0C00-\u0C7F]/ }, // Telugu
  { lang: 'kn', regex: /[\u0C80-\u0CFF]/ }, // Kannada
  { lang: 'bn', regex: /[\u0980-\u09FF]/ }, // Bengali / Assamese
  { lang: 'hi', regex: /[\u0900-\u097F]/ }, // Devanagari (Hindi / Marathi)
];

// Gemini 3.x Flash models "think" before answering by default, which adds
// several seconds. Short conversational answers don't need that, so we ask
// for 'low'. ('minimal' is rejected by newer models, so it is not the default.)
// Override with REACT_APP_GEMINI_THINKING = low | medium | high in .env.
const THINKING_LEVEL = process.env.REACT_APP_GEMINI_THINKING || 'low';

class SmartAIAgent {
  constructor() {
    this.apiKey = process.env.REACT_APP_GEMINI_API_KEY;
    this.genAI = this.apiKey ? new GoogleGenerativeAI(this.apiKey) : null;

    // Models are tried in order. gemini-2.5-flash is being retired by Google
    // (already returning "no longer available" for some keys), so it is NOT
    // in this list. If one model returns 404 the next is used automatically
    // and the one that worked is remembered in `activeModel`.
    // Put your preferred model first via REACT_APP_GEMINI_MODEL in .env.
    this.modelNames = [
      process.env.REACT_APP_GEMINI_MODEL,
      'gemini-3.6-flash',
      'gemini-3.7-flash',
      'gemini-3.5-flash',
      'gemini-3.5-flash-lite',
    ].filter((name, i, arr) => name && arr.indexOf(name) === i);
    this._models = {};
    this._retired = new Set(); // models that returned 404 — skipped from then on
    this.activeModel = null;   // last model that answered successfully (info only)
    this._noThinkingConfig = new Set(); // models that rejected the thinking setting

    // --- race-condition guard ---
    // Every call to ask() gets a sequence number. If a newer call has
    // started by the time an older one resolves, the older one is
    // cancelled and its result is discarded instead of being returned.
    this._requestSeq = 0;
    this._activeController = null;
    this.lastError = null;
  }

  /**
   * Guess the language from the characters the user actually typed.
   * Returns an ISO code from LANGUAGE_NAMES, or null if it looks like
   * plain Latin script (we let Gemini infer English vs. something else
   * from context in that case).
   */
  detectLanguageFromText(text) {
    for (const { lang, regex } of SCRIPT_RANGES) {
      if (regex.test(text)) return lang;
    }
    return null;
  }

  /**
   * Ask a question. This is the ONLY entry point the UI should call.
   *
   * @param {string} question
   * @param {string|null} preferredLang - optional explicit language code
   *   from a language-selector UI. If omitted, the language is detected
   *   from the question text itself.
   * @returns {Promise<{text: string, lang: string, stale: boolean, requestId: number}>}
   *
   * IMPORTANT for the calling UI (chat window / TTS): check `stale`
   * before rendering or speaking the result. If `stale` is true, a newer
   * question was asked before this one finished — discard it silently.
   * This is what prevents an old answer from being spoken over a newer
   * question's answer.
   */
  async ask(question, preferredLang = null) {
    const trimmed = (question || '').trim();
    if (!trimmed) {
      return { text: '', lang: preferredLang || 'en', stale: false, requestId: null };
    }

    // Cancel whatever request is currently in flight — the user has
    // moved on to a new question, so the old one no longer matters.
    if (this._activeController) {
      this._activeController.abort();
    }

    const requestId = ++this._requestSeq;
    const controller = new AbortController();
    this._activeController = controller;

    const lang = preferredLang || this.detectLanguageFromText(trimmed) || 'en';

    const text = await this._askGemini(trimmed, lang, controller.signal);

    const stale = requestId !== this._requestSeq;
    if (this._activeController === controller) {
      this._activeController = null;
    }

    return { text, lang, stale, requestId };
  }

  _getModel(name) {
    if (!this._models[name]) {
      const params = { model: name };
      // Lite models don't think by default, so they need no setting.
      if (!/lite/i.test(name) && !this._noThinkingConfig.has(name)) {
        params.generationConfig = { thinkingConfig: { thinkingLevel: THINKING_LEVEL } };
      }
      this._models[name] = this.genAI.getGenerativeModel(params);
    }
    return this._models[name];
  }

  // Turn a raw SDK error into one of a small set of types.
  _classifyError(error) {
    const status = error?.status || error?.response?.status;
    const msg = error?.message || '';

    if (error?.kind === 'empty') return 'empty';
    if ([500, 502, 503, 504].includes(status) || /overloaded|UNAVAILABLE|\b503\b/i.test(msg)) return 'unavailable';
    if (status === 404 || /not found|not supported|no longer available/i.test(msg)) return 'model';
    if (status === 401 || status === 403 || /API key not valid|PERMISSION_DENIED/i.test(msg)) return 'auth';
    if (status === 429 || /RESOURCE_EXHAUSTED|quota/i.test(msg)) return 'quota';
    if (/blocked|SAFETY/i.test(msg)) return 'blocked';
    if (typeof navigator !== 'undefined' && !navigator.onLine) return 'network';
    if (/Network|Failed to fetch/i.test(msg)) return 'network';
    return 'unknown';
  }

  async _askGemini(question, lang, signal) {
    if (!this.genAI) {
      this.lastError = { type: 'no-key', message: 'Gemini API key missing' };
      console.warn('⚠️ Gemini API key not found — set REACT_APP_GEMINI_API_KEY and restart the dev server');
      return this._errorMessage('no-key', lang);
    }

    const langName = LANGUAGE_NAMES[lang] || 'English';

    const prompt = `You are ReminiPlay Assistant, a warm and patient AI companion for elderly users in India's North Eastern Region.

⚠️ LANGUAGE RULE (most important instruction):
- Respond ONLY in ${langName}, using its native script throughout.
- Do not switch to English or mix scripts, unless the selected language is English.

HOW TO ANSWER:
- Actually think through the question and reason out a real answer — never fall back to a generic or templated reply.
- Be warm, respectful, and encouraging toward an elderly reader.
- Keep answers clear and conversational — usually 2 to 5 sentences, more only if the question genuinely needs it.
- Use simple, everyday language.
- For health-related questions, give a genuinely helpful answer but gently suggest seeing a doctor for anything serious. Never give specific medical dosages or prescriptions.
- If the question is ambiguous, ask a warm, brief clarifying question instead of guessing.

User's question: "${question}"`;

    // Skip models that already proved to be retired (404). If somehow all of
    // them are marked retired, start over rather than giving up.
    let names = this.modelNames.filter((n) => !this._retired.has(n));
    if (names.length === 0) {
      this._retired.clear();
      names = this.modelNames;
    }

    const RETRIES_PER_MODEL = 1;   // one quick retry for a busy (503) model
    const RETRY_DELAY_MS = 800;
    let failure = null;

    for (const modelName of names) {
      for (let attempt = 0; attempt <= RETRIES_PER_MODEL; attempt++) {
        if (signal?.aborted) return '';

        try {
          const model = this._getModel(modelName);
          const startedAt = Date.now();
          const result = await model.generateContent(prompt, { signal });
          const response = await result.response;
          const text = (response.text() || '').trim();

          if (!text) {
            const err = new Error('Gemini returned an empty response');
            err.kind = 'empty';
            throw err;
          }

          console.log(`⏱️ ${modelName} replied in ${Date.now() - startedAt} ms`);
          this.activeModel = modelName;
          this.lastError = null;
          return text;
        } catch (error) {
          if (error?.name === 'AbortError' || signal?.aborted) {
            // Expected when a newer question superseded this one — not a real error.
            return '';
          }

          // Model rejected the thinking setting (HTTP 400): rebuild it without
          // the setting and retry immediately. Doesn't use up a retry.
          if (
            error?.status === 400 &&
            /thinking/i.test(error?.message || '') &&
            !this._noThinkingConfig.has(modelName)
          ) {
            console.warn(`⚠️ ${modelName} rejected the thinking setting — retrying without it`);
            this._noThinkingConfig.add(modelName);
            delete this._models[modelName];
            attempt--;
            continue;
          }

          const type = this._classifyError(error);
          failure = { type, message: error?.message || '', model: modelName };
          console.error(
            `❌ Gemini error [${type}] on ${modelName} (attempt ${attempt + 1}):`,
            error?.message || error
          );

          if (type === 'model') this._retired.add(modelName);

          // Busy server: wait a moment and try this model once more.
          if (type === 'unavailable' && attempt < RETRIES_PER_MODEL) {
            await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY_MS));
            continue;
          }
          break; // give up on this model
        }
      }

      // Retired or overloaded model → try the next one in the chain.
      // Auth, quota, network, blocked, empty... would fail the same way on
      // every model, so stop and report instead.
      if (failure.type !== 'model' && failure.type !== 'unavailable') break;
    }

    this.lastError = failure;
    return this._errorMessage(failure.type, lang);
  }

  // The only remaining fixed text in this file. These fire ONLY when
  // Gemini itself could not be reached at all (no key, no network, quota
  // exhausted, bad model) — there is no "real" answer to think through
  // in that case, so a static message is unavoidable here.
  // NOTE: only `network` has its own wording; every other type
  // (no-key, model, auth, quota, blocked, empty, unknown) falls back to
  // `default`. Check the console / `aiAgent.lastError` for the real cause.
  _errorMessage(type, lang) {
    const sets = {
      network: {
        en: "I can't reach the internet right now. Please check your connection and try again.",
        hi: 'अभी मैं इंटरनेट से जुड़ नहीं पा रहा हूँ। कृपया अपना कनेक्शन जाँचें और फिर कोशिश करें।',
        as: 'মই এতিয়া ইণ্টাৰনেটৰ সৈতে সংযোগ কৰিব পাৰি নাই। অনুগ্ৰহ কৰি আপোনাৰ সংযোগ পৰীক্ষা কৰক।',
        bn: 'আমি এখন ইন্টারনেটের সাথে সংযুক্ত হতে পারছি না। অনুগ্রহ করে আপনার সংযোগ পরীক্ষা করুন।',
        mr: 'मी सध्या इंटरनेटशी जोडू शकत नाही. कृपया तुमचे कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.',
        gu: 'હું અત્યારે ઇન્ટરનેટ સાથે જોડાઈ શકતો નથી. કૃપા કરીને તમારું કનેક્શન તપાસો.',
        pa: 'ਮੈਂ ਹੁਣੇ ਇੰਟਰਨੈਟ ਨਾਲ ਜੁੜ ਨਹੀਂ ਪਾ ਰਿਹਾ। ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਕਨੈਕਸ਼ਨ ਜਾਂਚੋ।',
        or: 'ମୁଁ ବର୍ତ୍ତମାନ ଇଣ୍ଟରନେଟ ସହିତ ଯୋଡିହେବାରେ ଅସମର୍ଥ। ଦୟାକରି ଆପଣଙ୍କର ସଂଯୋଗ ଯାଞ୍ଚ କରନ୍ତୁ।',
        te: 'నేను ఇప్పుడు ఇంటర్నెట్‌తో కనెక్ట్ కాలేకపోతున్నాను. దయచేసి మీ కనెక్షన్‌ని తనిఖీ చేయండి.',
        ta: 'எனக்கு இப்போது இணையத்துடன் இணைய முடியவில்லை. உங்கள் இணைப்பைச் சரிபார்க்கவும்.',
        kn: 'ನನಗೆ ಈಗ ಇಂಟರ್ನೆಟ್‌ಗೆ ಸಂಪರ್ಕಿಸಲು ಸಾಧ್ಯವಾಗುತ್ತಿಲ್ಲ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ.',
      },
      default: {
        en: "I'm having a little trouble answering right now. Please try again in a moment.",
        hi: 'मुझे अभी उत्तर देने में थोड़ी परेशानी हो रही है। कृपया थोड़ी देर बाद फिर कोशिश करें।',
        as: 'মোৰ এতিয়া উত্তৰ দিয়াত অসুবিধা হৈছে। অনুগ্ৰহ কৰি কিছু সময় পিছত পুনৰ চেষ্টা কৰক।',
        bn: 'আমার এখন উত্তর দিতে একটু সমস্যা হচ্ছে। অনুগ্রহ করে কিছুক্ষণ পরে আবার চেষ্টা করুন।',
        mr: 'मला आत्ता उत्तर देण्यात थोडी अडचण येत आहे. कृपया थोड्या वेळाने पुन्हा प्रयत्न करा.',
        gu: 'મને હમણાં જવાબ આપવામાં થોડી મુશ્કેલી પડી રહી છે. કૃપા કરીને થોડી વાર પછી ફરી પ્રયાસ કરો.',
        pa: 'ਮੈਨੂੰ ਹੁਣੇ ਜਵਾਬ ਦੇਣ ਵਿੱਚ ਥੋੜ੍ਹੀ ਮੁਸ਼ਕਲ ਆ ਰਹੀ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਥੋੜ੍ਹੀ ਦੇਰ ਬਾਅਦ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
        or: 'ମୋର ବର୍ତ୍ତମାନ ଉତ୍ତର ଦେବାରେ ଛୋଟ ଅସୁବିଧା ହେଉଛି। ଦୟାକରି କିଛି ସମୟ ପରେ ପୁନର୍ବାର ପ୍ରୟାସ କରନ୍ତୁ।',
        te: 'నాకు ఇప్పుడు సమాధానం ఇవ్వడంలో కొంచెం ఇబ్బంది ఉంది. దయచేసి కొద్దిసేపు తర్వాత మళ్లీ ప్రయత్నించండి.',
        ta: 'எனக்கு இப்போது பதிலளிப்பதில் சிறு சிக்கல் உள்ளது. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.',
        kn: 'ನನಗೆ ಈಗ ಉತ್ತರಿಸಲು ಸ್ವಲ್ಪ ತೊಂದರೆಯಾಗುತ್ತಿದೆ. ದಯವಿಟ್ಟು ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
      },
    };

    const set = sets[type] || sets.default;
    const message = set[lang] || set.en;

    // Every non-network failure shares the same friendly text, which hides
    // the real cause. In development builds, append the cause so it is
    // visible on screen. (The TTS will read it aloud — that's dev only.)
    if (process.env.NODE_ENV === 'development') {
      const model = this.lastError?.model ? ` · ${this.lastError.model}` : '';
      return `${message} [debug: ${type}${model}]`;
    }
    return message;
  }
}

// Create singleton instance
const aiAgent = new SmartAIAgent();

export default aiAgent;